<script>
   import Skill from './Skill.svelte';

   export let system;
   let skills = system.skills;
   export let update;

</script>

<section>
   <Skill 
      name={"Acrobatics"}
      trained={skills.acrobatics.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Arcana"}
      trained={skills.arcana.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Athletics"}
      trained={skills.athletics.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Bluff"}
      trained={skills.bluff.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Diplomacy"}
      trained={skills.diplomacy.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Dungeoneering"}
      trained={skills.dungeoneering.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Endurance"}
      trained={skills.endurance.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Healing"}
      trained={skills.healing.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"History"}
      trained={skills.history.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Insight"}
      trained={skills.insight.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Intimidation"}
      trained={skills.intimidation.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Nature"}
      trained={skills.nature.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Perception"}
      trained={skills.perception.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Religion"}
      trained={skills.religion.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Stealth"}
      trained={skills.stealth.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Streetwise"}
      trained={skills.streetwise.trained}
      value={0}
      update={update}/>
   <Skill 
      name={"Thievery"}
      trained={skills.thievery.trained}
      value={0}
      update={update}/>
</section>

<style lang="scss">
</style>